scripts/create-distribution-image and related miscellaneous scripts work
Makefile:
- allow calling `make dist-image` with ISO name as parameter

scripts/build-live-iso:
- make logging pipe not mask error status (pipefail option)
- rename variable VAR to VARIANT
- put run-time summary in a function and set up as trap

scripts/create-distribution-image:
- create gzipped images with block maps and sha256sum for circulation
- takes FAT32 partition size as optional parameter, defaults to 1.5GiB
- always create images with 256MiB persistence partition
- calculate stick image size according to ISO / other partition sizes

scripts/functions.{bash,sh}:
- factor out get_image_name() and is_root_user_or_die() functions
- rename die_with_error() to die() and drop numeric error codes
- quote some variables, add braces to positional parameter

scripts/nspawn-debian-container:
- include bmap-tools and eatmyfnordata in package list
- alphabetically sort package dependency list
- speed up systemd-nspawn by turning off seccomp filters

scripts/stick-install:
- account for first partition offset of 16MiB in FAT32 partition size
- measure and print time installation takes
- add --help parameter for some usage info

diff --git a/scripts/build-live-iso b/scripts/build-live-iso
--- a/scripts/build-live-iso
+++ b/scripts/build-live-iso
@@ -4,6 +4,9 @@
 . "$(dirname $(realpath "${0}"))/functions.bash"
 cd_repo_root
 
+# let failures in pipe fail the whole pipe
+set -o pipefail
+
 # give some rudimentary help if requested
 case "${1}" in
     "-h")
@@ -18,37 +21,37 @@ esac
 select_build_variant() {
     shopt -s extglob
     OPTIONS=()
-    for VAR in $(command ls -Ltd variants.build/!(active|base_*|shared)/)
+    for VARIANT in $(command ls -Ltd variants.build/!(active|base_*|shared)/)
     do
-        NUMFILES=$(find "${VAR}" -type f -printf x | wc -c)
+        NUMFILES=$(find "${VARIANT}" -type f -printf x | wc -c)
         # THANKS https://stackoverflow.com/questions/4561895/how-to-recursively-find-the-latest-modified-file-in-a-directory
-        NEWESTFILE=$(find ${VAR} -type f -printf '%T@ %p\n'|sort -n|tail -n 1|cut -d" " -f2-)
+        NEWESTFILE=$(find ${VARIANT} -type f -printf '%T@ %p\n'|sort -n|tail -n 1|cut -d" " -f2-)
         [ -z "${NEWESTFILE}" ] && CHANGESTR="" || CHANGESTR=", last changed $(rel_fmt_low_precision $(stat --format='@%Y' "${NEWESTFILE}"))"
-        OPTIONS+=(${VAR#variants.build/} "(${NUMFILES} files${CHANGESTR})")
+        OPTIONS+=(${VARIANT#variants.build/} "(${NUMFILES} files${CHANGESTR})")
     done
     TEXT="Please choose the variant to build. (Build Variants named base_* or shared are not listed)"
     TITLE="SELECT LIVE SYSTEM BUILD VARIANT"
     display_menu "${TITLE}" "${TEXT}" "${OPTIONS[@]}"
 }
 
-build_main() {
-    if [ "$(id -u)" != "0" ]; then
-        die_with_error 3 "ERROR: no super-user privilege, please run as root or with sudo."
-    fi
+print_time_used() {
+    print_info "this took $(format_timespan $(($(date +%s) - STARTTIME))) (+ the work of many)"
+}
 
+build_main() {
     # if a BUILD_VARIANT is given as parameter, prefer that
-    [ -n "${1}" ] && BUILD_VARIANT=$1
+    [ -n "${1}" ] && BUILD_VARIANT=${1}
 
     # if not given, query user to visually select a variant
     [ -n "${BUILD_VARIANT}" ] || BUILD_VARIANT=$(select_build_variant)
 
-    [ -z ${BUILD_VARIANT} ] && die_with_error 1 "no BUILD_VARIANT selected. #saaad.."
+    [ -z "${BUILD_VARIANT}" ] && die "no BUILD_VARIANT selected. #saaad.."
 
     # chop off possible trailing slash and expose variable to sub processes
     export BUILD_VARIANT=${BUILD_VARIANT%/}
 
     # ensure the directory exists
-    [ -d "variants.build/${BUILD_VARIANT}" ] || die_with_error 2 "given BUILD_VARIANT=${BUILD_VARIANT} does not exist"
+    [ -d "variants.build/${BUILD_VARIANT}" ] || die "given BUILD_VARIANT=${BUILD_VARIANT} does not exist"
 
     print_info "Live-Stick Build Variant chosen: ${BUILD_VARIANT}\n"
 
@@ -82,12 +85,17 @@ build_main() {
         mkdir -p ../artifacts
 
         # and move generated files there
-        LB_IMAGE_NAME=$(sed -nr 's/LB_IMAGE_NAME="(.*)"$/\1/p' config/common)
+        LB_IMAGE_NAME=$(get_image_name)
         mv -iv ${LB_IMAGE_NAME}*.* ../artifacts/
-    } || print_error "FAILED"
+    } || die "lb build FAILED for ${BUILD_VARIANT}, check ${LOGFILE}"
 }
 
-STARTTIME=$(date +%s)
-build_main "${@}" |& tee build/build-live-iso.$(date '+%F.%H%Mh').log
+is_root_user_or_die
 
-print_info "this took $(format_timespan $(($(date +%s) - ${STARTTIME}))) (+ the work of many)"
+LOGFILE="build/build-live-iso.$(date '+%F.%H%Mh').log"
+
+# Measure time and print when exiting
+STARTTIME=$(date +%s)
+trap "print_time_used" EXIT SIGHUP SIGQUIT SIGTERM
+
+build_main "${@}" |& tee "${LOGFILE}"
