Add nspawn-debian-container and other script improvements

diff --git a/features/total_conversion_chicago95/prebuild-hooks/download-retro-os b/features/total_conversion_chicago95/prebuild-hooks/download-retro-os
--- a/features/total_conversion_chicago95/prebuild-hooks/download-retro-os
+++ b/features/total_conversion_chicago95/prebuild-hooks/download-retro-os
@@ -2,6 +2,8 @@
 
 . ../scripts/functions.bash
 
+check_dependencies qemu-utils libnbd-bin nbdkit
+
 PREFIX=config/includes.chroot
 TARGET_DIR=/usr/local/games/
 DEST_DIR=${PREFIX}/${TARGET_DIR#/}
@@ -13,22 +15,26 @@ mkdir -pv ${DEST_DIR}
 FILE=$(download_file_cached ${URL} ${FILENAME})
 cp -v ${FILE} ${DEST_DIR}
 
-if check_dependencies qemu-utils
-then
-    # fix vfbackup error.. and don't fail if this doesn't work
-    [ -d /sys/module/nbd ] || modprobe -v && {
-        TMPDIR=$(mktemp -d /tmp/stick.XXXXXX)
-        trap "rmdir ${TMPDIR}" EXIT SIGHUP SIGQUIT SIGTERM
-        NBD_DEV=/dev/nbd3
-        if [ $(cat /sys/class/block/${NBD_DEV##*/}/size) -eq 0 ]
-        then
-            qemu-nbd --connect=${NBD_DEV} "${DEST_DIR}/${FILENAME}"
-            sleep 3
-            mount -v ${NBD_DEV}p1 ${TMPDIR}
-            echo smartdrv >> ${TMPDIR}/AUTOEXEC.BAT
-            read foo
-            umount -v ${NBD_DEV}p1
-            qemu-nbd --disconnect ${NBD_DEV}
-        fi
-    } || true
-fi
+# fix vfbackup error.. and don't fail if this doesn't work
+[ -e /dev/loop-control ] && {
+    TMPDIR=$(mktemp -d /tmp/stick.XXXXXX)
+    MNTDIR=${TMPDIR}/mount
+    PARTDIR=${TMPDIR}/partition
+    VFAT=${PARTDIR}/vfat
+    SOCKET=${TMPDIR}/qemu-nbd.sock
+    TARGET="AUTOEXEC.BAT"
+
+    echo "rewriting ${TARGET}, just a second.."
+    trap "rmdir ${MNTDIR} ${PARTDIR} ${TMPDIR}" EXIT SIGHUP SIGQUIT SIGTERM
+
+    mkdir -p ${PARTDIR} ${MNTDIR}
+
+    qemu-nbd --socket=${SOCKET} "${DEST_DIR}/${FILENAME}" &
+    nbdfuse ${VFAT} --command nbdkit --stdin nbd socket=${SOCKET} --filter=partition partition=1 &
+    sleep 1
+    mount -o loop ${VFAT} ${MNTDIR} && \
+      echo smartdrv >> ${MNTDIR}/${TARGET}
+    umount --detach-loop ${MNTDIR}
+    sleep 1
+    umount ${PARTDIR}
+} || true
diff --git a/scripts/stick-install b/scripts/stick-install
--- a/scripts/stick-install
+++ b/scripts/stick-install
@@ -21,6 +21,7 @@ fi
 
 select_target_device() {
     OPTIONS=()
+    shopt -s nullglob
     for DEVICE in /dev/{sd?,vd?,loop*}
     do
         DEVNAME=${DEVICE#/dev/}
@@ -34,6 +35,7 @@ select_target_device() {
         grep -qs 1 /sys/block/${DEVNAME}/removable || [[ -d /sys/block/${DEVNAME}/loop ]] && \
             OPTIONS+=(${DEVICE} "${SIZESTR} ${BACKING}(${NUMPARTITIONS} $(ngettext 'partition' 'partitions' ${NUMPARTITIONS}))")
     done
+    [ -z ${OPTIONS} ] && echo "Could not find any suitable (loop) device!" && exit 5
     TEXT="Please choose the target device for installation of the live system.\n(Only removable block and loop devices with non-zero size are listed)"
     TITLE="SELECT LIVE SYSTEM TARGET DEVICE"
     display_menu "${TITLE}" "${TEXT}" "${OPTIONS[@]}"
@@ -321,8 +323,11 @@ BOOTOPTIONS+="persistence-encryption=none,luks "
 # if the label name matches, a persistence volume can be a directory, and image file or partition
 BOOTOPTIONS+="persistence-storage=directory,file,filesystem "
 
-# only scan removable media for persistence volumes
-BOOTOPTIONS+="persistence-media=removable-usb "
+if ! [[ "${DEVICE}" =~ ^/dev/loop[0-9]+ ]]
+then
+    # only scan removable media for persistence volumes
+    BOOTOPTIONS+="persistence-media=removable-usb "
+fi
 
 # Turn off spectre & co. security mitigations for a nice speed boost
 # FIXME: needs to be disabled if any exploits ever become known
